### ISSUE TITLE
Paper

### ISSUE THREAD

**Issue by way-thu** [bikaldev/MARL-TrafficLight#5]
Thanks for your sharing, is there any paper related to this code?

**Comment by bikaldev** [comment]
Yes, there is. Here's the link:
https://ieeexplore.ieee.org/abstract/document/9240060

**Comment by way-thu** [comment]
Much thanks for your reply, I noticed that the simulation in this project is conducted by SUMO, however, the paper said it is conduced by city-flow.  Don't you provide the source code but just an example?
![image](https://github.com/bikaldev/MARL-TrafficLight/assets/113359869/aeef768c-981a-4de2-b8aa-edaa562dc772)
