### ISSUE TITLE
simulator

### ISSUE THREAD

**Issue by way-thu** [bikaldev/MARL-TrafficLight#6]
Much thanks for your sharing, I noticed that the simulation in this project is conducted by SUMO, however, the paper said it is conduced by cityflow. Do you provide the source code but just an example? 
![image](https://github.com/bikaldev/MARL-TrafficLight/assets/113359869/b793490f-d563-4997-ad8b-7b887f37f912)

**Comment by bikaldev** [comment]
Yes, that is not our paper. The paper inspired the code. We used SUMO instead of CityFlow.

**Comment by way-thu** [comment]
> Yes, that is not our paper. The paper inspired the code. We used SUMO instead of CityFlow.

ok, I get it, thanks for your sharing again!
